In [1]:
from sklearn.preprocessing import PolynomialFeatures
import pickle
from sklearn.metrics import accuracy_score
from sklearn.metrics import roc_auc_score

In [2]:
from sklearn import linear_model
from sklearn.cross_validation import train_test_split
import numpy as np
import pandas as pd
from sklearn.grid_search import GridSearchCV



In [3]:
p = r'D:\test\training_features_3.csv'

In [4]:
df = np.array( pd.read_csv(p, sep = '\t'))
X = df[:,2:-1]
y = df[:,-1]

In [5]:
X

array([[ 0.12162162,  1.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.025     ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.10309278,  0.        ,  1.        , ...,  1.        ,
         0.        ,  1.        ],
       ..., 
       [ 0.00628141,  1.        ,  0.        , ...,  1.        ,
         0.        ,  0.        ],
       [ 0.04470588,  0.        ,  1.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.10120482,  1.        ,  1.        , ...,  1.        ,
         0.        ,  0.        ]])

In [112]:
#poly = PolynomialFeatures(2, interaction_only=True)
poly = PolynomialFeatures(2, interaction_only=True)
X = poly.fit_transform(X[:,:-1])

In [6]:
X = (X - np.mean(X, axis = 0))/(np.std(X, axis=0))

In [23]:
X = (1.0 * X) / (np.linalg.norm(X, axis = 0))

In [7]:
X

array([[ 0.95190612,  0.76252501, -1.14432024, ..., -0.24964564,
        -0.15902987, -0.23735633],
       [-0.65825975, -1.3114324 , -1.14432024, ..., -0.24964564,
        -0.15902987, -0.23735633],
       [ 0.64312945, -1.3114324 ,  0.87388124, ...,  4.00567779,
        -0.15902987,  4.21307489],
       ..., 
       [-0.97019862,  0.76252501, -1.14432024, ...,  4.00567779,
        -0.15902987, -0.23735633],
       [-0.32986804, -1.3114324 ,  0.87388124, ..., -0.24964564,
        -0.15902987, -0.23735633],
       [ 0.61166718,  0.76252501,  0.87388124, ...,  4.00567779,
        -0.15902987, -0.23735633]])

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

print X_train.shape, y_train.shape
print X_test.shape, y_test.shape

(2100L, 8L) (2100L,)
(900L, 8L) (900L,)


In [8]:
pd.read_csv(p, sep = '\t').head(8)

id_1       id_2  mut_friends  sex  city  country  graduation  \
0   18432098   21755561     0.121622    1     0        1           0   
1    3439886   18613417     0.025000    0     0        0           0   
2   21306589   22489153     0.103093    0     1        1           1   
3   16763113   22683000     0.087719    1     1        1           0   
4   30738600  136736228     0.021804    1     1        1           0   
5  182581472    5698686     0.000750    0     0        1           0   
6    8160531     601364     0.030556    1     0        1           0   
7    4353147   15746706     0.029801    1     0        1           0   

   university  school  school+uni  value  
0           0       0           0      1  
1           0       0           0      0  
2           1       0           1      1  
3           0       0           0      1  
4           0       0           0      1  
5           0       0           0      1  
6           0       0           0      1  
7           0       0           0      0

In [9]:
t = np.logspace(-5,0,100)
t

array([  1.00000000e-05,   1.12332403e-05,   1.26185688e-05,
         1.41747416e-05,   1.59228279e-05,   1.78864953e-05,
         2.00923300e-05,   2.25701972e-05,   2.53536449e-05,
         2.84803587e-05,   3.19926714e-05,   3.59381366e-05,
         4.03701726e-05,   4.53487851e-05,   5.09413801e-05,
         5.72236766e-05,   6.42807312e-05,   7.22080902e-05,
         8.11130831e-05,   9.11162756e-05,   1.02353102e-04,
         1.14975700e-04,   1.29154967e-04,   1.45082878e-04,
         1.62975083e-04,   1.83073828e-04,   2.05651231e-04,
         2.31012970e-04,   2.59502421e-04,   2.91505306e-04,
         3.27454916e-04,   3.67837977e-04,   4.13201240e-04,
         4.64158883e-04,   5.21400829e-04,   5.85702082e-04,
         6.57933225e-04,   7.39072203e-04,   8.30217568e-04,
         9.32603347e-04,   1.04761575e-03,   1.17681195e-03,
         1.32194115e-03,   1.48496826e-03,   1.66810054e-03,
         1.87381742e-03,   2.10490414e-03,   2.36448941e-03,
         2.65608778e-03,

In [10]:
params = {'C': t}
grid_searcher = GridSearchCV(linear_model.LogisticRegression(), params, cv=5, scoring='roc_auc', n_jobs=3)
%time grid_searcher.fit(X_train, y_train)
 
print grid_searcher.best_score_
print grid_searcher.best_estimator_
print grid_searcher.best_estimator_.coef_

#log_reg = pickle.dumps(grid_searcher)

Wall time: 1.86 s
0.599338770123
LogisticRegression(C=0.021544346900318846, class_weight=None, dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=100,
          multi_class='ovr', n_jobs=1, penalty='l2', random_state=None,
          solver='liblinear', tol=0.0001, verbose=0, warm_start=False)
[[ 0.19106473  0.0540554   0.04210721  0.15839372 -0.0897643  -0.06259698
   0.0569779   0.01326777]]


In [19]:
from sklearn.externals import joblib
joblib.dump(grid_searcher, 'D:/test/RFC/rfc.pkl') 

['D:/test/RFC/rfc.pkl',
 'D:/test/RFC/rfc.pkl_01.npy',
 'D:/test/RFC/rfc.pkl_02.npy',
 'D:/test/RFC/rfc.pkl_03.npy',
 'D:/test/RFC/rfc.pkl_04.npy',
 'D:/test/RFC/rfc.pkl_05.npy',
 'D:/test/RFC/rfc.pkl_06.npy',
 'D:/test/RFC/rfc.pkl_07.npy',
 'D:/test/RFC/rfc.pkl_08.npy',
 'D:/test/RFC/rfc.pkl_09.npy',
 'D:/test/RFC/rfc.pkl_10.npy',
 'D:/test/RFC/rfc.pkl_11.npy',
 'D:/test/RFC/rfc.pkl_12.npy',
 'D:/test/RFC/rfc.pkl_13.npy',
 'D:/test/RFC/rfc.pkl_14.npy',
 'D:/test/RFC/rfc.pkl_15.npy',
 'D:/test/RFC/rfc.pkl_16.npy',
 'D:/test/RFC/rfc.pkl_17.npy',
 'D:/test/RFC/rfc.pkl_18.npy',
 'D:/test/RFC/rfc.pkl_19.npy',
 'D:/test/RFC/rfc.pkl_20.npy',
 'D:/test/RFC/rfc.pkl_21.npy',
 'D:/test/RFC/rfc.pkl_22.npy',
 'D:/test/RFC/rfc.pkl_23.npy',
 'D:/test/RFC/rfc.pkl_24.npy',
 'D:/test/RFC/rfc.pkl_25.npy',
 'D:/test/RFC/rfc.pkl_26.npy',
 'D:/test/RFC/rfc.pkl_27.npy',
 'D:/test/RFC/rfc.pkl_28.npy',
 'D:/test/RFC/rfc.pkl_29.npy',
 'D:/test/RFC/rfc.pkl_30.npy',
 'D:/test/RFC/rfc.pkl_31.npy',
 'D:/test/RFC/r

In [16]:
params = {'n_estimators': [4000],'bootstrap':[True], 'max_depth':[4,5], 'random_state':[np.random.randint(1,10000000)], \
          'max_features':[1,2,3], 'max_leaf_nodes':[4,5], 'min_samples_split':[2], 'min_samples_leaf':[2]}

In [17]:
from sklearn.ensemble import RandomForestClassifier as RFC

#params = {'n_estimators': [4000]}
grid_searcher = GridSearchCV(RFC(), params, cv=5, scoring='roc_auc', n_jobs=3)
%time grid_searcher.fit(X_train, y_train)

print grid_searcher.best_score_
print grid_searcher.best_estimator_

Wall time: 4min 3s
0.601416383697
RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=4, max_features=2, max_leaf_nodes=4,
            min_samples_leaf=2, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=4000, n_jobs=1,
            oob_score=False, random_state=60904, verbose=0,
            warm_start=False)


In [16]:
print grid_searcher.best_estimator_.feature_importances_

[ 0.48952947  0.03913714  0.03232513  0.09610987  0.13127449  0.08372663
  0.06326715  0.06463013]


In [14]:
from sklearn.neighbors import KNeighborsClassifier as KNN

params = {'n_neighbors': range(1, 20, 2), 'weights' : ['distance']}
grid_searcher = GridSearchCV(KNN(), params, cv=5, scoring='roc_auc', n_jobs=3)
%time grid_searcher.fit(X_train, y_train)

print grid_searcher.best_score_
print grid_searcher.best_estimator_

Wall time: 1.19 s
0.550630365259
KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=19, p=2,
           weights='distance')


In [18]:
clf = grid_searcher.best_estimator_.fit(X_train, y_train)
results = clf.predict_proba(X_test)[:, 1]

#print results
print roc_auc_score(y_test, results)

[[ 0.18080554  0.81919446]
 [ 0.13606427  0.86393573]
 [ 0.16962005  0.83037995]
 ..., 
 [ 0.13389658  0.86610342]
 [ 0.23384518  0.76615482]
 [ 0.17019653  0.82980347]]


ValueError: bad input shape (900L, 2L)

In [79]:
logreg = linear_model.LogisticRegression(C=1e5)
logreg.fit(X_train, y_train)
Z = logreg.predict_proba(X_test)[:,1]


In [80]:
from sklearn.metrics import accuracy_score
#accuracy_score(y_test, Z)
roc_auc_score(y_test, Z)

0.54330370370370373

In [49]:
print y_test[:20]
print Z[:20]

[0 1 1 0 0 1 0 1 0 1 0 0 0 1 0 1 0 1 0 1]
[ 0.49961737  0.49976953  0.50698088  0.50531721  0.53213137  0.52416101
  0.55143169  0.51931299  0.49167515  0.49902354  0.49958412  0.50243335
  0.50588727  0.49567378  0.56801859  0.4998204   0.49677456  0.49939005
  0.50979014  0.50288662]
